name: grpc_web
description: Dart gRPC-Web sample client
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  grpc: any
  protobuf: any
  web: any

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.5
  lints: ^6.0.0
