name: googleapis
description: Dart gRPC client sample for Google APIs
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  async: any
  fixnum: any
  grpc: any
  protobuf: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
