name: interop
description: Dart gRPC interoperability test suite.
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  args: any
  async: any
  collection: any
  grpc: any
  protobuf: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
