name: metadata
description: Dart gRPC sample client and server.
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  async: any
  grpc: any
  protobuf: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
